import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import CourierProvider from '@/components/Courier/Provider';
import NavBar from '@/components/NavBar';
import theme from '@/theme';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import { cookies } from 'next/headers';
import { ulid } from 'ulid';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // setting a random ulid for demo purposes
    const cookieStore = cookies();
    let user_id = cookieStore.get('user_id');
    if (!user_id) {
        cookieStore.set('user_id', ulid());
    }
    return (
        <html lang="en">
            <body className={inter.className}>
                <AppRouterCacheProvider>
                    <ThemeProvider theme={theme}>
                        <CourierProvider>
                            <NavBar />
                            <div id="page">{children}</div>
                        </CourierProvider>
                    </ThemeProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
